/**
 * Standalone reference cards for the Library — Job Ready Edition.
 * Northstar Commerce examples throughout.
 */

function ref({
  id, subjectId, name, category, difficulty, contentType,
  definition, whatItDoes, whenToUse, stakeholderQuestion, syntax,
  componentBreakdown = [], sampleInput, expectedOutput,
  commonMistakes = [], relatedConcepts = [], practiceLink,
}) {
  return {
    id,
    subjectId,
    name,
    category,
    difficulty,
    contentType,
    definition,
    whatItDoes,
    whenToUse,
    stakeholderQuestion,
    syntax,
    componentBreakdown,
    sampleInput,
    expectedOutput,
    commonMistakes,
    relatedConcepts,
    practiceLink,
  };
}

export const jobReadyReferences = [
  // ── SQL ──────────────────────────────────────────────────────────
  ref({
    id: 'sql-ref-select',
    subjectId: 'sql',
    name: 'SELECT',
    category: 'Querying',
    difficulty: 'beginner',
    contentType: 'command',
    definition: 'Retrieves specified columns from one or more tables.',
    whatItDoes: 'Returns data without changing the database.',
    whenToUse: 'Exploring Northstar Commerce tables, building exports, validating row counts.',
    stakeholderQuestion: 'Can you send me customer names and emails from our database?',
    syntax: 'SELECT column1, column2\nFROM table_name;',
    componentBreakdown: [
      { part: 'SELECT', explanation: 'Lists columns to return, or * for all.' },
      { part: 'FROM', explanation: 'Names the source table.' },
    ],
    sampleInput: 'SELECT first_name, email FROM customers LIMIT 10;',
    expectedOutput: 'Two columns of customer data',
    commonMistakes: ['Using SELECT * on large production tables without LIMIT'],
    relatedConcepts: ['sql-ref-where', 'sql-ref-distinct'],
    practiceLink: '#/lesson/sql-lesson-select-basics',
  }),
  ref({
    id: 'sql-ref-where',
    subjectId: 'sql',
    name: 'WHERE',
    category: 'Filtering',
    difficulty: 'beginner',
    contentType: 'command',
    definition: 'Filters rows based on conditions.',
    whatItDoes: 'Keeps only rows that match your criteria.',
    whenToUse: 'Date ranges, regions, order status, revenue thresholds.',
    stakeholderQuestion: 'Show only West region orders over $500.',
    syntax: "SELECT * FROM orders\nWHERE region = 'West' AND amount > 500;",
    sampleInput: "WHERE order_date >= '2024-01-01'",
    expectedOutput: 'Subset of rows matching filters',
    commonMistakes: ['Using = NULL instead of IS NULL', 'Mixing AND/OR without parentheses'],
    relatedConcepts: ['sql-ref-select', 'sql-ref-group-by'],
    practiceLink: '#/lesson/sql-lesson-where-filtering',
  }),
  ref({
    id: 'sql-ref-group-by',
    subjectId: 'sql',
    name: 'GROUP BY',
    category: 'Aggregations',
    difficulty: 'intermediate',
    contentType: 'command',
    definition: 'Groups rows with shared values into summary rows.',
    whatItDoes: 'Enables COUNT, SUM, AVG per category.',
    whenToUse: 'Revenue by region, orders by month, customers by segment.',
    stakeholderQuestion: 'Break down Northstar revenue by product category.',
    syntax: 'SELECT category, SUM(quantity * unit_price) AS revenue\nFROM order_items oi\nJOIN products p ON oi.product_id = p.product_id\nGROUP BY category;',
    commonMistakes: ['Including non-aggregated columns not in GROUP BY'],
    relatedConcepts: ['sql-ref-having', 'sql-ref-inner-join'],
    practiceLink: '#/lesson/sql-lesson-group-by',
  }),
  ref({
    id: 'sql-ref-having',
    subjectId: 'sql',
    name: 'HAVING',
    category: 'Aggregations',
    difficulty: 'intermediate',
    contentType: 'command',
    definition: 'Filters groups after aggregation.',
    whatItDoes: 'Applies conditions to grouped results, not individual rows.',
    whenToUse: 'Categories with more than N orders, regions above revenue threshold.',
    stakeholderQuestion: 'Which regions had more than 100 orders last quarter?',
    syntax: 'SELECT region, COUNT(*) AS orders\nFROM orders\nGROUP BY region\nHAVING COUNT(*) > 100;',
    commonMistakes: ['Using HAVING without GROUP BY', 'Filtering rows with HAVING instead of WHERE'],
    relatedConcepts: ['sql-ref-group-by'],
    practiceLink: '#/lesson/sql-lesson-having',
  }),
  ref({
    id: 'sql-ref-inner-join',
    subjectId: 'sql',
    name: 'INNER JOIN',
    category: 'Joins',
    difficulty: 'intermediate',
    contentType: 'command',
    definition: 'Combines rows from two tables where join keys match.',
    whatItDoes: 'Returns matched rows only — unmatched rows are excluded.',
    whenToUse: 'Adding customer names to orders, product details to line items.',
    stakeholderQuestion: 'Add customer region to each order in the export.',
    syntax: 'SELECT o.order_id, c.region\nFROM orders o\nINNER JOIN customers c ON o.customer_id = c.customer_id;',
    commonMistakes: ['Missing ON clause', 'Joining on wrong key causing duplicate rows'],
    relatedConcepts: ['sql-ref-left-join'],
    practiceLink: '#/lesson/sql-lesson-inner-join',
  }),
  ref({
    id: 'sql-ref-left-join',
    subjectId: 'sql',
    name: 'LEFT JOIN',
    category: 'Joins',
    difficulty: 'intermediate',
    contentType: 'command',
    definition: 'Returns all rows from the left table plus matches from the right.',
    whatItDoes: 'Preserves every left-table row; NULLs where no match exists.',
    whenToUse: 'All customers including those with zero orders, all products including unsold SKUs.',
    stakeholderQuestion: 'List every customer, even if they never purchased.',
    syntax: 'SELECT c.customer_id, COUNT(o.order_id) AS orders\nFROM customers c\nLEFT JOIN orders o ON c.customer_id = o.customer_id\nGROUP BY c.customer_id;',
    commonMistakes: ['Using INNER JOIN when you need to keep non-matching rows'],
    relatedConcepts: ['sql-ref-inner-join'],
    practiceLink: '#/lesson/sql-lesson-left-join',
  }),
  ref({
    id: 'sql-ref-case',
    subjectId: 'sql',
    name: 'CASE',
    category: 'Logic',
    difficulty: 'intermediate',
    contentType: 'command',
    definition: 'Conditional logic inside a query.',
    whatItDoes: 'Creates derived columns based on IF/THEN rules.',
    whenToUse: 'Bucketing revenue tiers, labeling order status groups, conditional counts.',
    stakeholderQuestion: 'Tag each order as High or Standard value based on amount.',
    syntax: "CASE\n  WHEN amount >= 500 THEN 'High'\n  ELSE 'Standard'\nEND AS value_tier",
    commonMistakes: ['Missing ELSE clause', 'Overlapping conditions without clear order'],
    relatedConcepts: ['sql-ref-group-by'],
    practiceLink: '#/lesson/sql-lesson-case-expressions',
  }),
  ref({
    id: 'sql-ref-cte',
    subjectId: 'sql',
    name: 'Common Table Expression (CTE)',
    category: 'Advanced',
    difficulty: 'advanced',
    contentType: 'command',
    definition: 'A named temporary result set defined with WITH.',
    whatItDoes: 'Breaks complex queries into readable steps.',
    whenToUse: 'Multi-step analysis, reusable subqueries, readable pipeline logic.',
    stakeholderQuestion: 'Build monthly revenue in steps I can audit.',
    syntax: 'WITH monthly AS (\n  SELECT strftime(\'%Y-%m\', order_date) AS month,\n         SUM(amount) AS revenue\n  FROM orders\n  GROUP BY 1\n)\nSELECT * FROM monthly;',
    commonMistakes: ['Over-nesting CTEs without documenting each step'],
    relatedConcepts: ['sql-ref-subquery'],
    practiceLink: '#/lesson/sql-lesson-common-table-expressions',
  }),
  ref({
    id: 'sql-ref-window-row-number',
    subjectId: 'sql',
    name: 'ROW_NUMBER',
    category: 'Window Functions',
    difficulty: 'advanced',
    contentType: 'command',
    definition: 'Assigns a unique sequential number to rows within a partition.',
    whatItDoes: 'Ranks rows without collapsing them like GROUP BY.',
    whenToUse: 'Top-N per group, deduplication, ranking customers by spend.',
    stakeholderQuestion: 'Show the 3 most recent orders per customer.',
    syntax: 'ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date DESC) AS rn',
    commonMistakes: ['Forgetting ORDER BY in OVER clause', 'Using ROW_NUMBER when ties matter — use RANK'],
    relatedConcepts: ['sql-ref-group-by'],
    practiceLink: '#/lesson/sql-lesson-row-number',
  }),
  ref({
    id: 'sql-ref-distinct',
    subjectId: 'sql',
    name: 'DISTINCT',
    category: 'Querying',
    difficulty: 'beginner',
    contentType: 'command',
    definition: 'Removes duplicate rows from results.',
    whatItDoes: 'Returns unique values for selected columns.',
    whenToUse: 'Unique region lists, distinct customer counts exploration.',
    stakeholderQuestion: 'What regions does Northstar operate in?',
    syntax: 'SELECT DISTINCT region FROM customers;',
    commonMistakes: ['Using DISTINCT when GROUP BY is clearer for aggregates'],
    relatedConcepts: ['sql-ref-select'],
    practiceLink: '#/lesson/sql-lesson-distinct-aliases',
  }),

  // ── Excel ────────────────────────────────────────────────────────
  ref({
    id: 'excel-ref-sum',
    subjectId: 'excel',
    name: 'SUM',
    category: 'Functions',
    difficulty: 'beginner',
    contentType: 'function',
    definition: 'Adds all numbers in a range.',
    whatItDoes: 'Totals revenue, quantities, or any numeric column.',
    whenToUse: 'Monthly sales totals, order quantity rollups, budget sums.',
    stakeholderQuestion: 'What is total West region revenue in this export?',
    syntax: '=SUM(B2:B100)',
    sampleInput: 'Revenue column B, rows 2–100',
    expectedOutput: 'Single total value',
    commonMistakes: ['Including header row in range', 'Summing text-formatted numbers'],
    relatedConcepts: ['excel-ref-sumifs', 'excel-ref-pivot-table'],
    practiceLink: '#/lesson/excel-lesson-sum-average-min-and-max',
  }),
  ref({
    id: 'excel-ref-if',
    subjectId: 'excel',
    name: 'IF',
    category: 'Functions',
    difficulty: 'beginner',
    contentType: 'function',
    definition: 'Returns one value if a condition is true, another if false.',
    whatItDoes: 'Applies business rules in a single cell.',
    whenToUse: 'Flagging high-value orders, pass/fail KPI checks, tier labels.',
    stakeholderQuestion: 'Mark orders over $500 as High priority.',
    syntax: '=IF(D2>=500,"High","Standard")',
    commonMistakes: ['Nesting too many IFs — use IFS instead', 'Not handling blank cells'],
    relatedConcepts: ['excel-ref-sumifs'],
    practiceLink: '#/lesson/excel-lesson-if',
  }),
  ref({
    id: 'excel-ref-xlookup',
    subjectId: 'excel',
    name: 'XLOOKUP',
    category: 'Lookup',
    difficulty: 'intermediate',
    contentType: 'function',
    definition: 'Looks up a value and returns a corresponding result.',
    whatItDoes: 'Replaces VLOOKUP with flexible left/right lookup.',
    whenToUse: 'Pulling product name from SKU, customer segment from ID.',
    stakeholderQuestion: 'Add product category to the order export using product ID.',
    syntax: '=XLOOKUP(A2, Products[product_id], Products[category], "Not found")',
    commonMistakes: ['Lookup array not sorted when using approximate match', 'Wrong match mode'],
    relatedConcepts: ['excel-ref-index-match'],
    practiceLink: '#/lesson/excel-lesson-xlookup',
  }),
  ref({
    id: 'excel-ref-sumifs',
    subjectId: 'excel',
    name: 'SUMIFS',
    category: 'Functions',
    difficulty: 'intermediate',
    contentType: 'function',
    definition: 'Sums values that meet multiple criteria.',
    whatItDoes: 'Conditional aggregation without a pivot table.',
    whenToUse: 'Revenue for one region and one month, filtered totals.',
    stakeholderQuestion: 'Sum West region web-channel revenue for March.',
    syntax: '=SUMIFS(revenue_range, region_range, "West", channel_range, "web")',
    commonMistakes: ['Criteria ranges different size from sum range', 'Text criteria without quotes'],
    relatedConcepts: ['excel-ref-sum', 'excel-ref-countifs'],
    practiceLink: '#/lesson/excel-lesson-sumif-and-sumifs',
  }),
  ref({
    id: 'excel-ref-pivot-table',
    subjectId: 'excel',
    name: 'PivotTable',
    category: 'Analysis',
    difficulty: 'intermediate',
    contentType: 'workflow',
    definition: 'Interactive summary table that groups and aggregates data.',
    whatItDoes: 'Drag fields to rows, columns, and values for instant breakdowns.',
    whenToUse: 'Regional revenue by category, monthly trends, segment comparisons.',
    stakeholderQuestion: 'Build a pivot showing revenue by region and product category.',
    syntax: 'Insert → PivotTable → Select data range → Add Region to Rows, Category to Columns, Revenue to Values',
    commonMistakes: ['Not refreshing after source data changes', 'Mixing grain in source data'],
    relatedConcepts: ['excel-ref-sum', 'excel-ref-charts'],
    practiceLink: '#/lesson/excel-lesson-pivottables',
  }),
  ref({
    id: 'excel-ref-table',
    subjectId: 'excel',
    name: 'Excel Table',
    category: 'Data Management',
    difficulty: 'beginner',
    contentType: 'concept',
    definition: 'A structured range with headers, filters, and automatic expansion.',
    whatItDoes: 'Keeps formulas and pivots stable as data grows.',
    whenToUse: 'Any recurring Northstar export you analyze weekly.',
    stakeholderQuestion: 'Set up this sales export so formulas update when new rows arrive.',
    syntax: 'Select range → Insert → Table (Ctrl+T) → Check "My table has headers"',
    commonMistakes: ['Leaving blank rows inside the table', 'Not using structured references'],
    relatedConcepts: ['excel-ref-pivot-table'],
    practiceLink: '#/lesson/excel-lesson-cells-ranges-and-tables',
  }),
  ref({
    id: 'excel-ref-index-match',
    subjectId: 'excel',
    name: 'INDEX + MATCH',
    category: 'Lookup',
    difficulty: 'intermediate',
    contentType: 'function',
    definition: 'Flexible two-function lookup combination.',
    whatItDoes: 'Finds a value in one column and returns from another.',
    whenToUse: 'Lookups to the left, dynamic column selection, legacy workbook support.',
    stakeholderQuestion: 'Look up list price by product ID from a separate sheet.',
    syntax: '=INDEX(price_column, MATCH(product_id, id_column, 0))',
    commonMistakes: ['Omitting 0 for exact match in MATCH', 'Mismatched array lengths'],
    relatedConcepts: ['excel-ref-xlookup'],
    practiceLink: '#/lesson/excel-lesson-index-and-match',
  }),
  ref({
    id: 'excel-ref-conditional-formatting',
    subjectId: 'excel',
    name: 'Conditional Formatting',
    category: 'Visualization',
    difficulty: 'beginner',
    contentType: 'workflow',
    definition: 'Automatically formats cells based on rules.',
    whatItDoes: 'Highlights KPI exceptions, trends, and outliers visually.',
    whenToUse: 'Red/green revenue vs target, heat maps, duplicate detection.',
    stakeholderQuestion: 'Highlight regions below target in the dashboard sheet.',
    syntax: 'Home → Conditional Formatting → Highlight Cell Rules / Color Scales',
    commonMistakes: ['Applying to entire sheet slowing performance', 'Rules that conflict with each other'],
    relatedConcepts: ['excel-ref-if'],
    practiceLink: '#/lesson/excel-lesson-conditional-formatting',
  }),

  // ── Tableau ──────────────────────────────────────────────────────
  ref({
    id: 'tableau-ref-dimensions-measures',
    subjectId: 'tableau',
    name: 'Dimensions vs Measures',
    category: 'Fundamentals',
    difficulty: 'beginner',
    contentType: 'concept',
    definition: 'Dimensions are categorical fields; measures are numeric fields you aggregate.',
    whatItDoes: 'Determines how Tableau builds charts and aggregations.',
    whenToUse: 'Every time you connect Northstar data and choose chart fields.',
    stakeholderQuestion: 'Why does revenue sum but region does not?',
    syntax: 'Dimensions → Rows/Columns/Filters\nMeasures → Values (default aggregation: SUM)',
    commonMistakes: ['Dragging a numeric ID as a measure when it should be a dimension'],
    relatedConcepts: ['tableau-ref-calculated-field'],
    practiceLink: '#/lesson/tableau-lesson-dimensions-and-measures',
  }),
  ref({
    id: 'tableau-ref-calculated-field',
    subjectId: 'tableau',
    name: 'Calculated Field',
    category: 'Calculations',
    difficulty: 'intermediate',
    contentType: 'function',
    definition: 'A custom formula column built from existing fields.',
    whatItDoes: 'Creates metrics like profit margin, conversion rate, or buckets.',
    whenToUse: 'Profit = revenue − cost, order size tiers, year-over-year flags.',
    stakeholderQuestion: 'Add profit margin to every product in the dashboard.',
    syntax: '[Revenue] - [Cost]\n// or\nIF [Amount] > 500 THEN "High" ELSE "Standard" END',
    commonMistakes: ['Mixing aggregate and non-aggregate in same formula without FIXED LOD'],
    relatedConcepts: ['tableau-ref-lod-fixed'],
    practiceLink: '#/lesson/tableau-lesson-calculated-fields',
  }),
  ref({
    id: 'tableau-ref-parameter',
    subjectId: 'tableau',
    name: 'Parameter',
    category: 'Interactivity',
    difficulty: 'intermediate',
    contentType: 'concept',
    definition: 'A user-controlled input that drives calculations or filters.',
    whatItDoes: 'Lets viewers change thresholds, date ranges, or top-N values.',
    whenToUse: 'Adjustable revenue threshold, selectable comparison year, top-N products.',
    stakeholderQuestion: 'Let leadership change the top-N product count on the dashboard.',
    syntax: 'Create Parameter → Reference in calculated field or filter → Show parameter control',
    commonMistakes: ['Parameter not connected to any calculation or filter'],
    relatedConcepts: ['tableau-ref-filter'],
    practiceLink: '#/lesson/tableau-lesson-parameters',
  }),
  ref({
    id: 'tableau-ref-filter',
    subjectId: 'tableau',
    name: 'Filter',
    category: 'Interactivity',
    difficulty: 'beginner',
    contentType: 'workflow',
    definition: 'Restricts data shown in a view or dashboard.',
    whatItDoes: 'Narrows analysis to region, date range, segment, or category.',
    whenToUse: 'Regional dashboards, date sliders, category drill-down.',
    stakeholderQuestion: 'Add a region filter to the sales dashboard.',
    syntax: 'Drag field to Filters shelf → Choose range, list, or condition',
    commonMistakes: ['Context filters slowing performance on large datasets'],
    relatedConcepts: ['tableau-ref-parameter'],
    practiceLink: '#/lesson/tableau-lesson-filters-and-sorting',
  }),
  ref({
    id: 'tableau-ref-lod-fixed',
    subjectId: 'tableau',
    name: 'FIXED LOD Expression',
    category: 'Calculations',
    difficulty: 'advanced',
    contentType: 'function',
    definition: 'Computes a value at a specified dimension level independent of the view.',
    whatItDoes: 'Enables customer-level totals on a product-level chart.',
    whenToUse: 'Customer lifetime value on order rows, percent of total at different grain.',
    stakeholderQuestion: 'Show each order as a percent of that customer\'s total spend.',
    syntax: '{ FIXED [Customer ID] : SUM([Revenue]) }',
    commonMistakes: ['Using INCLUDE/EXCLUDE when FIXED is clearer'],
    relatedConcepts: ['tableau-ref-calculated-field'],
    practiceLink: '#/lesson/tableau-lesson-calculated-fields',
  }),
  ref({
    id: 'tableau-ref-dashboard',
    subjectId: 'tableau',
    name: 'Dashboard',
    category: 'Design',
    difficulty: 'intermediate',
    contentType: 'workflow',
    definition: 'A collection of views on one canvas with shared interactivity.',
    whatItDoes: 'Combines KPIs, trends, and filters into one decision screen.',
    whenToUse: 'Executive reviews, marketing performance, regional ops monitoring.',
    stakeholderQuestion: 'Build one screen with revenue trend, regional map, and top products.',
    syntax: 'Dashboard → New Dashboard → Drag sheets → Add filters → Align layout',
    commonMistakes: ['Too many views without visual hierarchy', 'Unlabeled axes on executive dashboards'],
    relatedConcepts: ['tableau-ref-filter'],
    practiceLink: '#/lesson/tableau-lesson-building-interactive-dashboards',
  }),

  // ── Power BI ─────────────────────────────────────────────────────
  ref({
    id: 'power-bi-ref-calculate',
    subjectId: 'power-bi',
    name: 'CALCULATE',
    category: 'DAX',
    difficulty: 'intermediate',
    contentType: 'function',
    definition: 'Evaluates an expression in a modified filter context.',
    whatItDoes: 'The most important DAX function for conditional metrics.',
    whenToUse: 'Revenue for West only, sales excluding returns, same period last year.',
    stakeholderQuestion: 'Show West region revenue on the KPI card regardless of page filters.',
    syntax: 'West Revenue = CALCULATE(SUM(Orders[Revenue]), Customers[Region] = "West")',
    commonMistakes: ['Using CALCULATE when a simple filter suffices', 'Filter column from unrelated table without relationship'],
    relatedConcepts: ['power-bi-ref-measure', 'power-bi-ref-filter-context'],
    practiceLink: '#/lesson/power-bi-lesson-calculate-and-filter-context',
  }),
  ref({
    id: 'power-bi-ref-measure',
    subjectId: 'power-bi',
    name: 'Measure',
    category: 'DAX',
    difficulty: 'beginner',
    contentType: 'concept',
    definition: 'A dynamic calculation evaluated at query time based on filter context.',
    whatItDoes: 'Aggregates correctly across visuals unlike calculated columns.',
    whenToUse: 'Total revenue, order count, average order value, conversion rate.',
    stakeholderQuestion: 'Create a Total Revenue measure that works on any visual.',
    syntax: 'Total Revenue = SUM(Orders[Revenue])',
    commonMistakes: ['Using calculated column for something that should be a measure', 'Not using DIVIDE for ratios'],
    relatedConcepts: ['power-bi-ref-calculate'],
    practiceLink: '#/lesson/power-bi-lesson-measures-and-calculated-columns',
  }),
  ref({
    id: 'power-bi-ref-star-schema',
    subjectId: 'power-bi',
    name: 'Star Schema',
    category: 'Modeling',
    difficulty: 'intermediate',
    contentType: 'concept',
    definition: 'A fact table surrounded by dimension tables with one-to-many relationships.',
    whatItDoes: 'Simplifies DAX and improves performance for Northstar analytics.',
    whenToUse: 'Modeling orders (fact) with customers, products, and date dimensions.',
    stakeholderQuestion: 'Structure our Northstar model for fast report performance.',
    syntax: 'FactOrders → DimCustomer, DimProduct, DimDate (one-to-many from dimension to fact)',
    commonMistakes: ['Snowflaking dimensions unnecessarily', 'Bi-directional filters without reason'],
    relatedConcepts: ['power-bi-ref-relationship'],
    practiceLink: '#/lesson/power-bi-lesson-star-schema',
  }),
  ref({
    id: 'power-bi-ref-power-query',
    subjectId: 'power-bi',
    name: 'Power Query',
    category: 'Data Prep',
    difficulty: 'beginner',
    contentType: 'workflow',
    definition: 'ETL tool for importing, cleaning, and transforming data before modeling.',
    whatItDoes: 'Applies repeatable steps: remove columns, fix types, merge tables.',
    whenToUse: 'Cleaning Northstar CSV exports, combining files, unpivoting columns.',
    stakeholderQuestion: 'Clean the monthly order export before it hits the report.',
    syntax: 'Transform Data → Applied Steps: Source, Changed Type, Removed Columns, Filtered Rows',
    commonMistakes: ['Not documenting transformation steps', 'Hard-coding filters that should be parameters'],
    relatedConcepts: ['power-bi-ref-star-schema'],
    practiceLink: '#/lesson/power-bi-lesson-power-query-data-cleaning',
  }),
  ref({
    id: 'power-bi-ref-divide',
    subjectId: 'power-bi',
    name: 'DIVIDE',
    category: 'DAX',
    difficulty: 'beginner',
    contentType: 'function',
    definition: 'Safe division that handles divide-by-zero.',
    whatItDoes: 'Returns alternate result instead of error when denominator is zero.',
    whenToUse: 'Conversion rates, margin percentages, growth rates.',
    stakeholderQuestion: 'Calculate conversion rate without errors when sessions are zero.',
    syntax: 'Conversion Rate = DIVIDE(SUM(Orders[Orders]), SUM(Sessions[Sessions]), 0)',
    commonMistakes: ['Using / operator without zero check'],
    relatedConcepts: ['power-bi-ref-measure'],
    practiceLink: '#/lesson/power-bi-lesson-dax-fundamentals',
  }),
  ref({
    id: 'power-bi-ref-filter-context',
    subjectId: 'power-bi',
    name: 'Filter Context',
    category: 'DAX',
    difficulty: 'advanced',
    contentType: 'concept',
    definition: 'The set of filters applied to a measure when it is evaluated.',
    whatItDoes: 'Explains why the same measure shows different values on different visuals.',
    whenToUse: 'Debugging unexpected totals, writing CALCULATE, understanding slicers.',
    stakeholderQuestion: 'Why does Total Revenue change when I click a region on the chart?',
    syntax: 'Visual filters + page filters + report filters + relationships = filter context',
    commonMistakes: ['Expecting measures to ignore active slicers without CALCULATE override'],
    relatedConcepts: ['power-bi-ref-calculate'],
    practiceLink: '#/lesson/power-bi-lesson-calculate-and-filter-context',
  }),
  ref({
    id: 'power-bi-ref-totalytd',
    subjectId: 'power-bi',
    name: 'TOTALYTD',
    category: 'Time Intelligence',
    difficulty: 'intermediate',
    contentType: 'function',
    definition: 'Calculates year-to-date total for a measure.',
    whatItDoes: 'Running cumulative total from start of year to current date.',
    whenToUse: 'YTD revenue vs target, cumulative order counts, executive KPI cards.',
    stakeholderQuestion: 'Show year-to-date revenue on the monthly trend chart.',
    syntax: 'Revenue YTD = TOTALYTD(SUM(Orders[Revenue]), DimDate[Date])',
    commonMistakes: ['Missing a proper date table marked as date table', 'Incomplete year in filter context'],
    relatedConcepts: ['power-bi-ref-measure'],
    practiceLink: '#/lesson/power-bi-lesson-dax-fundamentals',
  }),

  // ── Python ───────────────────────────────────────────────────────
  ref({
    id: 'python-ref-dataframe',
    subjectId: 'python',
    name: 'pandas DataFrame',
    category: 'pandas',
    difficulty: 'beginner',
    contentType: 'concept',
    definition: 'A two-dimensional labeled table for structured data analysis.',
    whatItDoes: 'Stores Northstar orders, customers, and products like a spreadsheet in code.',
    whenToUse: 'Any tabular analysis — filtering, grouping, merging, exporting.',
    stakeholderQuestion: 'Load our order export and summarize revenue by region.',
    syntax: 'import pandas as pd\ndf = pd.read_csv("orders.csv")\ndf.head()',
    commonMistakes: ['Not inspecting df.info() for data types after loading'],
    relatedConcepts: ['python-ref-read-csv', 'python-ref-groupby'],
    practiceLink: '#/lesson/python-lesson-pandas-series-and-dataframes',
  }),
  ref({
    id: 'python-ref-read-csv',
    subjectId: 'python',
    name: 'read_csv',
    category: 'pandas',
    difficulty: 'beginner',
    contentType: 'function',
    definition: 'Loads a CSV file into a DataFrame.',
    whatItDoes: 'Imports Northstar exports for analysis in Python.',
    whenToUse: 'Starting any pandas analysis from exported data.',
    stakeholderQuestion: 'Load last month\'s order file into Python.',
    syntax: 'orders = pd.read_csv("northstar_orders.csv", parse_dates=["order_date"])',
    commonMistakes: ['Not parsing date columns', 'Wrong encoding for special characters'],
    relatedConcepts: ['python-ref-dataframe'],
    practiceLink: '#/lesson/python-lesson-reading-csv-and-excel-files',
  }),
  ref({
    id: 'python-ref-groupby',
    subjectId: 'python',
    name: 'groupby',
    category: 'pandas',
    difficulty: 'intermediate',
    contentType: 'function',
    definition: 'Splits data into groups and applies aggregations.',
    whatItDoes: 'Computes revenue by region, order count by segment, etc.',
    whenToUse: 'Segmented KPIs equivalent to SQL GROUP BY or Excel pivot.',
    stakeholderQuestion: 'Group Northstar orders by region and sum revenue.',
    syntax: 'df.groupby("region")["revenue"].sum().sort_values(ascending=False)',
    commonMistakes: ['Forgetting .reset_index() when you need a flat DataFrame'],
    relatedConcepts: ['python-ref-dataframe', 'python-ref-merge'],
    practiceLink: '#/lesson/python-lesson-sorting-and-grouping',
  }),
  ref({
    id: 'python-ref-merge',
    subjectId: 'python',
    name: 'merge',
    category: 'pandas',
    difficulty: 'intermediate',
    contentType: 'function',
    definition: 'Combines two DataFrames on shared key columns.',
    whatItDoes: 'Joins orders to customers or products like SQL JOIN.',
    whenToUse: 'Enriching order data with customer region or product category.',
    stakeholderQuestion: 'Add customer segment to each order row.',
    syntax: 'pd.merge(orders, customers, on="customer_id", how="left")',
    commonMistakes: ['Many-to-many merge creating duplicate rows', 'Wrong join key name'],
    relatedConcepts: ['python-ref-groupby'],
    practiceLink: '#/lesson/python-lesson-merging-dataframes',
  }),
  ref({
    id: 'python-ref-loc',
    subjectId: 'python',
    name: 'loc',
    category: 'pandas',
    difficulty: 'beginner',
    contentType: 'function',
    definition: 'Label-based selection of rows and columns.',
    whatItDoes: 'Filters and slices DataFrames by column name and condition.',
    whenToUse: 'Selecting West region rows, specific columns for export.',
    stakeholderQuestion: 'Filter orders to West region with order_id and revenue only.',
    syntax: 'df.loc[df["region"] == "West", ["order_id", "revenue"]]',
    commonMistakes: ['Using chained indexing instead of loc', 'SettingWithCopyWarning from slices'],
    relatedConcepts: ['python-ref-dataframe'],
    practiceLink: '#/lesson/python-lesson-selecting-and-filtering-data',
  }),
  ref({
    id: 'python-ref-fillna',
    subjectId: 'python',
    name: 'fillna',
    category: 'Cleaning',
    difficulty: 'beginner',
    contentType: 'function',
    definition: 'Replaces missing values with a specified value or method.',
    whatItDoes: 'Handles NULL/missing data before analysis.',
    whenToUse: 'Filling missing region with "Unknown", zero-filling numeric gaps.',
    stakeholderQuestion: 'Replace missing support ticket categories before analysis.',
    syntax: 'df["category"].fillna("Unknown")\ndf["revenue"].fillna(0)',
    commonMistakes: ['Filling without understanding why values are missing'],
    relatedConcepts: ['python-ref-dataframe'],
    practiceLink: '#/lesson/python-lesson-cleaning-missing-and-duplicate-data',
  }),
  ref({
    id: 'python-ref-matplotlib',
    subjectId: 'python',
    name: 'matplotlib pyplot',
    category: 'Visualization',
    difficulty: 'intermediate',
    contentType: 'function',
    definition: 'Python library for creating charts and plots.',
    whatItDoes: 'Visualizes trends, comparisons, and distributions.',
    whenToUse: 'Revenue trend lines, regional bar charts, distribution histograms.',
    stakeholderQuestion: 'Chart monthly Northstar revenue for the stakeholder deck.',
    syntax: 'import matplotlib.pyplot as plt\nplt.bar(regions, revenue)\nplt.title("Revenue by Region")\nplt.show()',
    commonMistakes: ['Missing axis labels on stakeholder-facing charts'],
    relatedConcepts: ['python-ref-groupby'],
    practiceLink: '#/lesson/python-lesson-matplotlib-visualization',
  }),

  // ── Statistics ───────────────────────────────────────────────────
  ref({
    id: 'stats-ref-mean-median',
    subjectId: 'statistics',
    name: 'Mean and Median',
    category: 'Descriptive',
    difficulty: 'beginner',
    contentType: 'concept',
    definition: 'Mean is the average; median is the middle value when sorted.',
    whatItDoes: 'Summarizes typical order value or customer spend.',
    whenToUse: 'Reporting average order value — median when outliers skew the mean.',
    stakeholderQuestion: 'What is typical order value for Northstar customers?',
    syntax: 'Mean: sum(values) / n\nMedian: middle value of sorted list',
    commonMistakes: ['Using mean when outliers distort the picture'],
    relatedConcepts: ['stats-ref-standard-deviation'],
    practiceLink: '#/lesson/statistics-lesson-mean-median-and-mode',
  }),
  ref({
    id: 'stats-ref-standard-deviation',
    subjectId: 'statistics',
    name: 'Standard Deviation',
    category: 'Descriptive',
    difficulty: 'intermediate',
    contentType: 'concept',
    definition: 'Measures how spread out values are from the mean.',
    whatItDoes: 'Quantifies variability in order amounts, daily sales, or response times.',
    whenToUse: 'Understanding consistency of regional performance.',
    stakeholderQuestion: 'How much do daily order counts vary from the average?',
    syntax: 'σ = sqrt( Σ(x - mean)² / n )',
    commonMistakes: ['Confusing standard deviation with standard error'],
    relatedConcepts: ['stats-ref-mean-median', 'stats-ref-confidence-interval'],
    practiceLink: '#/lesson/statistics-lesson-variance-and-standard-deviation',
  }),
  ref({
    id: 'stats-ref-confidence-interval',
    subjectId: 'statistics',
    name: 'Confidence Interval',
    category: 'Inference',
    difficulty: 'intermediate',
    contentType: 'concept',
    definition: 'A range likely to contain the true population parameter.',
    whatItDoes: 'Communicates uncertainty in sample estimates.',
    whenToUse: 'Survey results, sampled conversion rates, estimated average spend.',
    stakeholderQuestion: 'We sampled 200 customers — what range likely contains true average spend?',
    syntax: 'CI = sample_mean ± (critical_value × standard_error)',
    commonMistakes: ['Saying "95% chance the true value is in this interval" — wording matters'],
    relatedConcepts: ['stats-ref-hypothesis-test'],
    practiceLink: '#/lesson/statistics-lesson-confidence-intervals',
  }),
  ref({
    id: 'stats-ref-hypothesis-test',
    subjectId: 'statistics',
    name: 'Hypothesis Test',
    category: 'Inference',
    difficulty: 'intermediate',
    contentType: 'workflow',
    definition: 'Formal procedure to test a claim about a population using sample data.',
    whatItDoes: 'Determines if an observed difference is statistically significant.',
    whenToUse: 'A/B tests, campaign lift, before/after policy changes.',
    stakeholderQuestion: 'Did the new checkout flow significantly improve conversion?',
    syntax: '1. State H₀ and H₁\n2. Choose test (t-test, chi-square)\n3. Calculate p-value\n4. Compare to α (e.g. 0.05)',
    commonMistakes: ['Confusing statistical significance with practical significance'],
    relatedConcepts: ['stats-ref-p-value', 'stats-ref-ab-test'],
    practiceLink: '#/lesson/statistics-lesson-hypothesis-testing-and-a-b-testing',
  }),
  ref({
    id: 'stats-ref-p-value',
    subjectId: 'statistics',
    name: 'p-value',
    category: 'Inference',
    difficulty: 'intermediate',
    contentType: 'concept',
    definition: 'Probability of seeing results at least this extreme if H₀ is true.',
    whatItDoes: 'Helps decide whether to reject the null hypothesis.',
    whenToUse: 'Interpreting A/B test results, regression coefficients.',
    stakeholderQuestion: 'Is p = 0.03 strong enough evidence to launch the new feature?',
    syntax: 'If p < α (typically 0.05), reject H₀',
    commonMistakes: ['Treating p-value as effect size', 'P-hacking by testing many variants'],
    relatedConcepts: ['stats-ref-hypothesis-test'],
    practiceLink: '#/lesson/statistics-lesson-hypothesis-testing-and-a-b-testing',
  }),
  ref({
    id: 'stats-ref-correlation',
    subjectId: 'statistics',
    name: 'Correlation',
    category: 'Regression',
    difficulty: 'intermediate',
    contentType: 'concept',
    definition: 'Measures linear relationship strength between two variables (-1 to +1).',
    whatItDoes: 'Identifies whether two metrics move together.',
    whenToUse: 'Marketing spend vs revenue, session duration vs conversion.',
    stakeholderQuestion: 'Does higher marketing spend correlate with more orders?',
    syntax: 'r = correlation(marketing_spend, order_count)',
    commonMistakes: ['Assuming correlation implies causation'],
    relatedConcepts: ['stats-ref-regression'],
    practiceLink: '#/lesson/statistics-lesson-correlation-and-regression-fundamentals',
  }),
  ref({
    id: 'stats-ref-ab-test',
    subjectId: 'statistics',
    name: 'A/B Test',
    category: 'Experiments',
    difficulty: 'intermediate',
    contentType: 'workflow',
    definition: 'Randomized experiment comparing control vs treatment groups.',
    whatItDoes: 'Measures whether a change caused a measurable improvement.',
    whenToUse: 'Northstar checkout tests, email subject lines, pricing experiments.',
    stakeholderQuestion: 'Did variant B increase conversion enough to roll out?',
    syntax: 'Randomize users → Measure metric per group → Run significance test → Check practical lift',
    commonMistakes: ['Stopping early when results look good', 'Not pre-registering success metric'],
    relatedConcepts: ['stats-ref-hypothesis-test', 'stats-ref-p-value'],
    practiceLink: '#/lesson/statistics-lesson-hypothesis-testing-and-a-b-testing',
  }),
  ref({
    id: 'stats-ref-normal-distribution',
    subjectId: 'statistics',
    name: 'Normal Distribution',
    category: 'Distributions',
    difficulty: 'beginner',
    contentType: 'concept',
    definition: 'Bell-shaped symmetric distribution defined by mean and standard deviation.',
    whatItDoes: 'Foundation for many statistical tests and confidence intervals.',
    whenToUse: 'Checking if sample size is adequate, interpreting z-scores.',
    stakeholderQuestion: 'Are our order values roughly normal or heavily skewed?',
    syntax: '~68% within 1σ, ~95% within 2σ, ~99.7% within 3σ of mean',
    commonMistakes: ['Assuming normality without checking skewness on real business data'],
    relatedConcepts: ['stats-ref-mean-median', 'stats-ref-standard-deviation'],
    practiceLink: '#/lesson/statistics-lesson-distributions-and-normal-distribution',
  }),
];
