/**
 * Full lesson content for initial SQL representative set.
 */
export const sqlLessons = [
  {
    id: 'sql-lesson-intro-databases',
    subjectId: 'sql',
    moduleId: 'sql-module-fundamentals',
    title: 'What Is a Database?',
    difficulty: 'beginner',
    estimatedMinutes: 12,
    prerequisites: [],
    learningObjectives: [
      'Explain what a database is in plain English',
      'Describe why businesses rely on databases for analytics',
      'Identify common database types used in analytics roles',
    ],
    plainEnglish: 'A database is an organized collection of data stored electronically so it can be searched, updated, and analyzed efficiently. Think of it as a structured filing system that multiple people and applications can use at the same time.',
    whatItDoes: 'Stores business data — customers, orders, products, employees — in a consistent structure so analysts can answer questions reliably.',
    whenToUse: 'Whenever you need to analyze data that lives in a company system rather than a one-off spreadsheet.',
    stakeholderQuestion: 'Can you pull last quarter\'s sales by region from our database?',
    walkthrough: 'Most analytics work starts with a relational database. Data is organized into tables. Each table holds records about one type of thing — customers, orders, or products. Analysts use SQL to ask questions across these tables.',
    syntax: '-- A database contains schemas, tables, and rows\n-- Example: orders table with columns id, customer_id, amount, order_date',
    componentBreakdown: [
      { part: 'Database', explanation: 'The overall container holding all related data for an application or business unit.' },
      { part: 'Table', explanation: 'A collection of rows about one entity, like orders or customers.' },
      { part: 'Row', explanation: 'One record — a single order, customer, or product.' },
      { part: 'Column', explanation: 'One attribute of the entity, such as order_date or amount.' },
    ],
    sampleInput: 'A retail company stores 2.4 million order rows across 5 years in an orders table.',
    expectedOutput: 'An analyst can query total revenue by month without opening individual spreadsheets.',
    commonMistakes: [
      'Assuming all company data is in one table',
      'Confusing a database with a spreadsheet workbook',
      'Not checking whether you have access to production or a sandbox copy',
    ],
    bestPractices: [
      'Always confirm which environment you are querying (dev vs production)',
      'Document table names and business definitions before writing complex queries',
      'Start with small exploratory queries before building full reports',
    ],
    guidedExample: {
      description: 'A marketing manager asks how many customers placed orders last month. The answer lives in the orders and customers tables — not in a slide deck.',
      steps: ['Identify the orders table', 'Find the order_date column', 'Count distinct customer_id values for last month'],
    },
    guidedPractice: { exerciseId: 'sql-exercise-explore-orders' },
    independentChallenge: null,
    knowledgeCheck: { quizId: 'sql-quiz-intro-databases' },
    relatedConcepts: ['sql-ref-select', 'sql-ref-table'],
    projectConnection: 'Foundation for the Retail Sales Analysis project',
    tags: ['fundamentals', 'database'],
  },
  {
    id: 'sql-lesson-select-basics',
    subjectId: 'sql',
    moduleId: 'sql-module-querying',
    title: 'SELECT Basics',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    prerequisites: ['sql-lesson-intro-databases'],
    learningObjectives: [
      'Write a basic SELECT statement to retrieve columns from a table',
      'Select all columns or specific columns',
      'Understand the order of a simple query',
    ],
    plainEnglish: 'SELECT is how you ask a database to show you data. You choose which columns you want and which table they come from.',
    whatItDoes: 'Retrieves data from one or more columns in a table without changing the underlying data.',
    whenToUse: 'Whenever you need to explore data, build a report, or verify what is stored in a table.',
    stakeholderQuestion: 'Can you send me a list of customer names and their email addresses?',
    walkthrough: 'Every SELECT query needs at least two parts: what columns you want (SELECT) and where they live (FROM). Start simple — pull a few columns, scan the results, then refine.',
    syntax: 'SELECT column1, column2\nFROM table_name;',
    componentBreakdown: [
      { part: 'SELECT', explanation: 'Lists the columns to return. Use * to return all columns.' },
      { part: 'FROM', explanation: 'Names the table containing the data.' },
      { part: 'Semicolon', explanation: 'Ends the statement. Good habit even when optional.' },
    ],
    sampleInput: 'Table: customers\nColumns: customer_id, first_name, last_name, email',
    expectedOutput: 'customer_id | first_name | last_name | email\n1 | Maria | Lopez | maria@example.com',
    commonMistakes: [
      'Forgetting the FROM clause',
      'Using SELECT * on very wide tables in production without LIMIT',
      'Misspelling column or table names (SQL is case-sensitive in some systems)',
    ],
    bestPractices: [
      'Name specific columns instead of SELECT * when building reports',
      'Use LIMIT while exploring unfamiliar tables',
      'Alias unclear column names for readable output',
    ],
    guidedExample: {
      description: 'Retrieve customer names and emails from the customers table.',
      sql: 'SELECT first_name, last_name, email\nFROM customers\nLIMIT 10;',
    },
    guidedPractice: { exerciseId: 'sql-exercise-select-columns' },
    independentChallenge: { exerciseId: 'sql-exercise-select-challenge' },
    knowledgeCheck: { quizId: 'sql-quiz-select-basics' },
    relatedConcepts: ['sql-ref-select', 'sql-ref-limit'],
    projectConnection: 'First step in exploring the retail orders dataset',
    tags: ['select', 'querying'],
  },
  {
    id: 'sql-lesson-where-filtering',
    subjectId: 'sql',
    moduleId: 'sql-module-querying',
    title: 'Filtering with WHERE',
    difficulty: 'beginner',
    estimatedMinutes: 18,
    prerequisites: ['sql-lesson-select-basics'],
    learningObjectives: [
      'Filter rows using WHERE with comparison operators',
      'Combine conditions with AND and OR',
      'Use IN, BETWEEN, LIKE, and IS NULL appropriately',
    ],
    plainEnglish: 'WHERE narrows your results to only the rows that match your conditions — like filtering a spreadsheet to show only West region sales.',
    whatItDoes: 'Filters rows after the table is identified but before sorting or grouping.',
    whenToUse: 'When stakeholders ask for a subset of data: a date range, a region, a status, or customers matching criteria.',
    stakeholderQuestion: 'How many orders did we receive from California customers in March?',
    walkthrough: 'Add WHERE after FROM. Each condition compares a column to a value. Chain conditions with AND (both must be true) or OR (either can be true). Use parentheses when mixing AND and OR.',
    syntax: "SELECT columns\nFROM table\nWHERE column = 'value'\n  AND other_column > 100;",
    componentBreakdown: [
      { part: 'WHERE', explanation: 'Introduces row-level filters.' },
        { part: '=, >, <', explanation: 'Comparison operators for numbers, dates, and text.' },
      { part: 'AND / OR', explanation: 'Combine multiple conditions.' },
      { part: 'LIKE', explanation: "Pattern matching with % wildcard — e.g., WHERE name LIKE 'A%'." },
      { part: 'IN', explanation: 'Match any value in a list — e.g., WHERE status IN (\'shipped\', \'delivered\').' },
      { part: 'IS NULL', explanation: 'Find missing values — use IS NULL, not = NULL.' },
    ],
    sampleInput: 'orders table with region, order_date, amount',
    expectedOutput: 'Only rows where region = \'West\' and order_date between \'2024-01-01\' and \'2024-03-31\'',
    commonMistakes: [
      'Using = NULL instead of IS NULL',
      'Forgetting quotes around text values',
      'AND/OR precedence bugs without parentheses',
    ],
    bestPractices: [
      'Filter early to reduce data scanned',
      'Use explicit date ranges instead of vague terms',
      'Test filters with COUNT(*) before pulling wide result sets',
    ],
    guidedExample: {
      description: 'Find West region orders over $500.',
      sql: "SELECT order_id, customer_id, amount, region\nFROM orders\nWHERE region = 'West'\n  AND amount > 500\nORDER BY amount DESC;",
    },
    guidedPractice: { exerciseId: 'sql-exercise-where-filter' },
    independentChallenge: { exerciseId: 'sql-exercise-where-challenge' },
    knowledgeCheck: { quizId: 'sql-quiz-where-filtering' },
    relatedConcepts: ['sql-ref-where', 'sql-ref-like'],
    projectConnection: 'Filter retail orders by category and date range',
    tags: ['where', 'filtering'],
  },
  {
    id: 'sql-lesson-order-by-limit',
    subjectId: 'sql',
    moduleId: 'sql-module-querying',
    title: 'Sorting and LIMIT',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    prerequisites: ['sql-lesson-where-filtering'],
    learningObjectives: [
      'Sort results with ORDER BY ascending or descending',
      'Limit result rows with LIMIT',
      'Combine filtering, sorting, and limiting in one query',
    ],
    plainEnglish: 'ORDER BY arranges your results — highest to lowest, newest to oldest. LIMIT caps how many rows come back, which is essential when exploring large tables.',
    whatItDoes: 'ORDER BY sorts the final result set. LIMIT restricts the number of rows returned.',
    whenToUse: 'Top-N reports, recent activity lists, and safe exploration of large datasets.',
    stakeholderQuestion: 'Who are our top 10 customers by total spend this year?',
    walkthrough: 'Write SELECT and FROM first, add WHERE if needed, then ORDER BY column DESC for highest-first. Finish with LIMIT 10 for top ten rows.',
    syntax: 'SELECT columns\nFROM table\nWHERE conditions\nORDER BY column DESC\nLIMIT 10;',
    componentBreakdown: [
      { part: 'ORDER BY', explanation: 'Sorts results. ASC is default (low to high). DESC reverses order.' },
      { part: 'LIMIT', explanation: 'Returns only the first N rows after sorting.' },
    ],
    sampleInput: 'orders sorted by amount descending',
    expectedOutput: 'Ten rows with the highest order amounts first',
    commonMistakes: [
      'Using LIMIT without ORDER BY when you need top-N (order is undefined)',
      'Sorting by the wrong column',
    ],
    bestPractices: [
      'Always ORDER BY before LIMIT for meaningful top-N queries',
      'Use LIMIT during exploration',
    ],
    guidedExample: {
      sql: 'SELECT order_id, amount, order_date\nFROM orders\nORDER BY amount DESC\nLIMIT 5;',
    },
    guidedPractice: { exerciseId: 'sql-exercise-order-limit' },
    independentChallenge: null,
    knowledgeCheck: null,
    relatedConcepts: ['sql-ref-order-by', 'sql-ref-limit'],
    projectConnection: 'Identify top-selling products in retail analysis',
    tags: ['order-by', 'limit'],
  },
  {
    id: 'sql-lesson-distinct-aliases',
    subjectId: 'sql',
    moduleId: 'sql-module-querying',
    title: 'DISTINCT and Aliases',
    difficulty: 'beginner',
    estimatedMinutes: 15,
    prerequisites: ['sql-lesson-select-basics'],
    learningObjectives: [
      'Remove duplicate values with DISTINCT',
      'Rename columns with aliases using AS',
      'Write readable queries for stakeholders',
    ],
    plainEnglish: 'DISTINCT shows unique values only. Aliases rename columns in your output so reports make sense to non-technical readers.',
    whatItDoes: 'DISTINCT deduplicates rows in the result. AS gives a column a display name.',
    whenToUse: 'Counting unique customers, listing categories, or presenting cleaner column headers in reports.',
    stakeholderQuestion: 'How many unique product categories do we sell?',
    walkthrough: 'SELECT DISTINCT category FROM products returns each category once. SELECT amount AS order_total makes headers readable.',
    syntax: 'SELECT DISTINCT column AS alias_name\nFROM table;',
    componentBreakdown: [
      { part: 'DISTINCT', explanation: 'Returns unique combinations of selected columns.' },
      { part: 'AS', explanation: 'Optional alias for column or table names.' },
    ],
    sampleInput: 'products table with repeated categories',
    expectedOutput: 'One row per unique category',
    commonMistakes: [
      'Using DISTINCT when GROUP BY is more appropriate for aggregates',
      'Aliases with spaces without quotes in some SQL dialects',
    ],
    bestPractices: [
      'Use meaningful alias names matching business terminology',
      'Combine DISTINCT with COUNT for unique counts',
    ],
    guidedExample: {
      sql: 'SELECT DISTINCT region AS sales_region\nFROM orders\nORDER BY sales_region;',
    },
    guidedPractice: null,
    independentChallenge: null,
    knowledgeCheck: null,
    relatedConcepts: ['sql-ref-distinct'],
    projectConnection: 'List unique customer segments',
    tags: ['distinct', 'aliases'],
  },
  {
    id: 'sql-lesson-aggregate-functions',
    subjectId: 'sql',
    moduleId: 'sql-module-aggregates',
    title: 'Aggregate Functions',
    difficulty: 'intermediate',
    estimatedMinutes: 20,
    prerequisites: ['sql-lesson-where-filtering'],
    learningObjectives: [
      'Use SUM, AVG, COUNT, MIN, and MAX to summarize data',
      'Understand the difference between COUNT(*) and COUNT(column)',
      'Combine aggregates with WHERE filters',
    ],
    plainEnglish: 'Aggregate functions collapse many rows into one summary number — total sales, average order value, or number of orders.',
    whatItDoes: 'Computes a single value from a set of rows: sums, averages, counts, minimums, maximums.',
    whenToUse: 'KPI dashboards, executive summaries, and any question starting with "how many" or "what is the total."',
    stakeholderQuestion: 'What was our total revenue and average order value last quarter?',
    walkthrough: 'SELECT SUM(amount), AVG(amount), COUNT(*) FROM orders WHERE order_date >= \'2024-01-01\'. Each aggregate runs over all rows matching the filter.',
    syntax: 'SELECT COUNT(*), SUM(amount), AVG(amount), MIN(amount), MAX(amount)\nFROM orders;',
    componentBreakdown: [
      { part: 'COUNT(*)', explanation: 'Counts all rows including nulls.' },
      { part: 'COUNT(column)', explanation: 'Counts non-null values in that column.' },
      { part: 'SUM / AVG', explanation: 'Total and average of numeric columns.' },
      { part: 'MIN / MAX', explanation: 'Smallest and largest values.' },
    ],
    sampleInput: '500 order rows with amounts',
    expectedOutput: 'One summary row: count=500, sum=125000, avg=250',
    commonMistakes: [
      'Mixing aggregate and non-aggregate columns without GROUP BY',
      'AVG including null or zero values unintentionally',
    ],
    bestPractices: [
      'Round averages for currency display',
      'Validate COUNT vs business definition of "order"',
    ],
    guidedExample: {
      sql: 'SELECT COUNT(*) AS order_count,\n       SUM(amount) AS total_revenue,\n       ROUND(AVG(amount), 2) AS avg_order_value\nFROM orders;',
    },
    guidedPractice: { exerciseId: 'sql-exercise-aggregates' },
    independentChallenge: null,
    knowledgeCheck: null,
    relatedConcepts: ['sql-ref-count', 'sql-ref-sum'],
    projectConnection: 'Calculate KPIs for retail sales report',
    tags: ['aggregates', 'sum', 'count'],
  },
  {
    id: 'sql-lesson-group-by',
    subjectId: 'sql',
    moduleId: 'sql-module-aggregates',
    title: 'GROUP BY and HAVING',
    difficulty: 'intermediate',
    estimatedMinutes: 22,
    prerequisites: ['sql-lesson-aggregate-functions'],
    learningObjectives: [
      'Group aggregates by category using GROUP BY',
      'Filter groups with HAVING',
      'Explain the difference between WHERE and HAVING',
    ],
    plainEnglish: 'GROUP BY breaks your data into buckets — per region, per month, per product — and calculates metrics for each bucket. HAVING filters those buckets after they are formed.',
    whatItDoes: 'Creates one result row per unique combination of grouped columns with aggregate values.',
    whenToUse: 'Regional comparisons, monthly trends, product category performance.',
    stakeholderQuestion: 'Show me total revenue by region, but only regions above $50,000.',
    walkthrough: 'SELECT region, SUM(amount) FROM orders GROUP BY region HAVING SUM(amount) > 50000. WHERE filters rows before grouping; HAVING filters groups after.',
    syntax: 'SELECT region, SUM(amount) AS revenue\nFROM orders\nGROUP BY region\nHAVING SUM(amount) > 50000\nORDER BY revenue DESC;',
    componentBreakdown: [
      { part: 'GROUP BY', explanation: 'Columns that define each group.' },
      { part: 'HAVING', explanation: 'Filter on aggregate values, applied after GROUP BY.' },
      { part: 'WHERE vs HAVING', explanation: 'WHERE filters individual rows; HAVING filters grouped results.' },
    ],
    sampleInput: 'Orders across North, South, East, West regions',
    expectedOutput: 'One row per region with revenue totals',
    commonMistakes: [
      'Including non-grouped columns in SELECT',
      'Using WHERE to filter on aggregate values',
    ],
    bestPractices: [
      'Group by the smallest set of columns that answers the question',
      'Name aggregates clearly in aliases',
    ],
    guidedExample: {
      sql: 'SELECT region, COUNT(*) AS orders, SUM(amount) AS revenue\nFROM orders\nGROUP BY region\nORDER BY revenue DESC;',
    },
    guidedPractice: { exerciseId: 'sql-exercise-group-by' },
    independentChallenge: null,
    knowledgeCheck: null,
    relatedConcepts: ['sql-ref-group-by'],
    projectConnection: 'Sales by category in retail project',
    tags: ['group-by', 'having'],
  },
  {
    id: 'sql-lesson-inner-join',
    subjectId: 'sql',
    moduleId: 'sql-module-joins',
    title: 'INNER JOIN',
    difficulty: 'intermediate',
    estimatedMinutes: 25,
    prerequisites: ['sql-lesson-group-by'],
    learningObjectives: [
      'Combine two tables with INNER JOIN',
      'Write join conditions using primary and foreign keys',
      'Select columns from multiple tables',
    ],
    plainEnglish: 'INNER JOIN matches rows from two tables based on a shared key — like linking orders to customer names using customer_id.',
    whatItDoes: 'Returns only rows where a match exists in both tables.',
    whenToUse: 'When you need columns from related tables — customer name with each order, product name with order line items.',
    stakeholderQuestion: 'Can I get order amounts with the customer name and email for last month?',
    walkthrough: 'FROM orders INNER JOIN customers ON orders.customer_id = customers.customer_id. The ON clause defines how rows relate.',
    syntax: 'SELECT o.order_id, c.first_name, c.last_name, o.amount\nFROM orders o\nINNER JOIN customers c ON o.customer_id = c.customer_id;',
    componentBreakdown: [
      { part: 'INNER JOIN', explanation: 'Keeps only matching rows from both tables.' },
      { part: 'ON', explanation: 'Equality condition linking the tables, usually key to foreign key.' },
      { part: 'Table alias', explanation: 'Short names (o, c) keep queries readable.' },
    ],
    sampleInput: 'orders and customers tables linked by customer_id',
    expectedOutput: 'Order rows enriched with customer first and last name',
    commonMistakes: [
      'Missing join condition causing a Cartesian product',
      'Joining on the wrong column',
    ],
    bestPractices: [
      'Always specify join keys explicitly',
      'Use table aliases for multi-table queries',
    ],
    guidedExample: {
      sql: 'SELECT o.order_id, o.amount, c.email\nFROM orders o\nINNER JOIN customers c ON o.customer_id = c.customer_id\nLIMIT 10;',
    },
    guidedPractice: { exerciseId: 'sql-exercise-inner-join' },
    independentChallenge: null,
    knowledgeCheck: null,
    relatedConcepts: ['sql-ref-inner-join'],
    projectConnection: 'Enrich orders with customer demographics',
    tags: ['joins', 'inner-join'],
  },
];
